#!/usr/bin/env python
# -*- coding: utf-8 -*-
# emacs: -*- mode: python; py-indent-offset: 4; indent-tabs-mode: nil -*-
# vi: set ft=python sts=4 ts=4 sw=4 et:
# @Author: oesteban
# @Date:   2015-10-08 13:07:21
# @Last Modified by:   oesteban
# @Last Modified time: 2015-10-08 14:53:20


if __name__ == "__main__":
    import logging
    import argparse
    import os.path as op
    from qap.viz.reports import workflow_report
    from qap.script_utils import qap_types

    logger = logging.getLogger('report')

    parser = argparse.ArgumentParser()
    req = parser.add_argument_group("Required Inputs")
    req.add_argument('-i', '--input_csv', type=str, required=True,
                     help='filepath to csv file generated by qap')

    req.add_argument(
        '-m', '--qap_mode', type=str, help='report type',
        choices=qap_types, required=True)

    args = parser.parse_args()
    in_csv = args.input_csv
    qap_type = args.qap_mode
    out_dir = op.dirname(in_csv)

    reports = workflow_report(in_csv, qap_type,
                              out_dir=out_dir, full_reports=True)

    for k, v in reports.iteritems():
        if v['success']:
            logger.info('Written report (%s) in %s' % (k, v['path']))
